### ISSUE TITLE
Erreur lors de la création d'un Tour +

### ISSUE THREAD

**Issue by LNR4** [valunair/crewissues#2]
Bonjour, 
Sur la page Admin Tour, lors de la création d'un tour, on arrive au final sur la page suivante.

![image](https://user-images.githubusercontent.com/72234455/110807855-b988a980-8283-11eb-913a-995facefb10d.png)

**Comment by lunairdev** [comment]
Le fichier contenant les étapes n'a pas été joint.

**Comment by LNR4** [comment]
Je viens de réessayer plusieurs fois, en allant chercher le fichier, ça ne fonctionne pas !

**Comment by lunairdev** [comment]
Effectivement l'erreur ne vient pas de l'a tu n'as pas mis de photo de profil au tour

**Comment by LNR4** [comment]
Et comment tu as fait pour insérer les autres Tours, vu qu'il n'y a aucune photo !!

**Comment by lunairdev** [comment]
Bah j'ai ajouté une photo je l'affiche juste pas encore faut que je l'ajoute ca

**Comment by LNR4** [comment]
ok, ça marche;. dès que j'ai 5 minutes, je corrige et met une photo !! merci !!
