### ISSUE TITLE
Résultats financiers lors d'un long haul !

### ISSUE THREAD

**Issue by LNR4** [valunair/crewissues#4]
Bonjour,
Ci joint l'image d'un rapport de vol financier, 
Vol avec un B736 de Paris à Cayenne...
Si on continu comme ça.. la Cie va fermer ses portes !! :-))
![image](https://user-images.githubusercontent.com/72234455/111013139-9e5e8c80-839e-11eb-8fe4-764c321f9dc8.png)

**Comment by lunairdev** [comment]
Bah faut remplir son avion avec fret + pax... Car bah sinon j'y suis pour rien 1l de JET-A1 coute le même prix hein
